
import os

WINDOW_WIDTH = 600
WINDOW_HEIGHT = 400
WINDOW_POSITION_RIGHT = 10
WINDOW_POSITION_DOWN = 10

PATH_DIRECTORY = os.path.dirname(__file__)
PATH_IMAGE = os.path.join(PATH_DIRECTORY, 'images')


COLOR_BACKGROUND = "#202124"
COLOR_BLACK = "#000"
COLOR_WHITE = "#fff"
